#!/bin/sh /etc/rc.common

START=50

start() {

/overlay/.local/bin/staticDHCPd > /overlay/log/statichdcpd.log 2>&1 &

}

stop() {

kill -TERM `cat /var/run/staticdhcpd.pid`
rm /var/run/staticdhcpd.pid

}
